#!/usr/bin/python
from trading import Market, Order, Indicator, Serie, MARKET_PRICE
from trading.strategy import Strategy 
from trading.backtest import BacktestMarket
from trading.evolver import Evolver
from util import save_as_js
import logging, time, sys

log = logging.getLogger("strategy")


def main():

#    logging.basicConfig(level=logging.DEBUG)

    if len(sys.argv) > 1:
        market = BacktestMarket()
        market.add_strategy( Strategy( "Bankruptsy", [market["SBER"]], 11 ) )
        market.load( sys.argv[1] )
        if len(sys.argv) > 2:
            save_as_js( market["SBER"], sys.argv[2] )
    else:
        try:
            from quik.market import QuikMarket
        except ImportError:
            print("Quik connector not available")
            sys.exit(1)

        market = QuikMarket( "c:\\quik-bcs","QuikDDE" )
        market.add_strategy( Strategy( "Bankruptsy", [market["SBER03"]] ) )
        market.run()

def profile():
    import hotshot, hotshot.stats
    prof = hotshot.Profile("trade.prof")
    prof.runcall(main)
    prof.close()
    stats = hotshot.stats.load("trade.prof")
    stats.strip_dirs()
    stats.sort_stats('time', 'calls')
    stats.print_stats(50)

if __name__ == "__main__":
#    ev = Evolver( sys.argv[1] )
#    ev.run()
    main()
